### ISSUE TITLE
DSM 7

### ISSUE THREAD

**Issue by bolshukhin** [michealespinola/syno.plexupdate#13]
SYNO.PLEX UPDATE SCRIPT v3.0.2

 * CONFIGURATION FILE (config.ini) IS MISSING, CREATING DEFAULT SETUP...

         Script: syno.plexupdate.sh v3.0.2
     Script Dir: /volume1/Geroev_Avenue_18
    Running Ver: 3.0.2
     Online Ver: 3.0.2
       Released: 2021-03-31 11:55:38+03:00 (37+ days old)
                 * No new version found.

cat: '/Failed to get log file 255/Preferences.xml': No such file or directory
cat: '/Failed to get log file 255/Preferences.xml': No such file or directory
       Synology: DS218+ (x86_64), DSM 7.0-41222 Update 0
       Plex Dir: /Failed to get log file 255
     Plex Token: 
    Running Ver: 
     Online Ver: 1.22.3.4392 (Public Channel)
       Released: 2021-04-20 13:20:12+03:00 (17+ days old)
                 * Newer version found!

    New Package: PlexMediaServer-1.22.3.4392-d7c624def-x86_64_**DSM6**.spk
    Package Age: 17+ days old (7+ required for install)

INSTALLING NEW PACKAGE:
----------------------------------------
2021-05-07 16:02:27 URL:https://downloads.plex.tv/plex-media-server-new/1.22.3.4392-d7c624def/synology/PlexMediaServer-1.22.3.4392-d7c624def-x86_64_DSM6.spk [117944320/117944320] -> "/volume1/Geroev_Avenue_18/Archive/Packages/PlexMediaServer-1.22.3.4392-d7c624def-x86_64_DSM6.spk" [1]
{"action":"prepare","error":{"code":0},"stage":"prepare","success":true}

{"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":319,"description":"invalid package privilege content"},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"Plex Media Server","packageName":"Plex Media Server","spk":"/volume1/Geroev_Avenue_18/Archive/Packages/PlexMediaServer-1.22.3.4392-d7c624def-x86_64_DSM6.spk","stage":"install_failed","success":false,"username":""}],"success":false}

{"action":"prepare","error":{"code":150,"description":"Failed to load package info"},"stage":"prepare","success":false}
----------------------------------------

    Update from: 
             to: 1.22.3.4392 failed!

How I can change DSM6 to DSM7?
DS218+, DSM7. Actual link for me is https://downloads.plex.tv/plex-media-server-new/1.23.0.4497-a1b1f3c10/synology-dsm7/PlexMediaServer-1.23.0.4497-a1b1f3c10-x86_64_**DSM7**.spk

<img width="850" alt="Снимок экрана 2021-05-07 в 15 58 25" src="https://user-images.githubusercontent.com/61148703/117453699-eb4d8200-af4d-11eb-8d75-8a918153c2e5.png">

Tnx

**Comment by michealespinola** [comment]
DSM 7 is still beta. I have no means of testing/developing for it, so I cannot support it at this time.
