### ISSUE TITLE
[3.0.2] Is there a configuration option to facilitate the use of Plex Pass versions?

### ISSUE THREAD

**Issue by apainter2** [michealespinola/syno.plexupdate#20]
Great script, and I am using version 3.0.2 of the script.

Is there a way I can configure it to utilise the Plex Pass versions of PMS? Currently, the public channel is 1.24.3.5033, whereas my Plex Pass version is 1.24.4.5081.

I am unable to see a configuration option within the config.ini.

Is it possible to use the Plex Pass channel?

Thanks,

**Comment by apainter2** [comment]
Great script, and I am using version 3.0.2 of the script.

Is there a way I can configure it to utilise the Plex Pass versions of PMS? Currently, the public channel is 1.24.3.5033, whereas my Plex Pass version is 1.24.4.5081.

I am unable to see a configuration option within the config.ini.

Is it possible to use the Plex Pass channel?

Thanks,

**Comment by isr25** [comment]
It follows your Plex server configuration in Plex -> Settings -> General -> Server Update Channel. It can be either Beta or Public.

**Comment by michealespinola** [comment]
As you likely already know, but I'm going to say it for any future people with the same question: The update script automatically follows what you have configured in your Plex Media Server.
