### ISSUE TITLE
DSM7 support?

### ISSUE THREAD

**Issue by hobbesjaap** [michealespinola/syno.plexupdate#21]
First of all: a big thank you for putting this together! Takes the headache out of a manual Plex update on Synology every once in a while.

I know some people went the Watchtower/Dockerised route, but I prefer to have the Plex app as a native DSM app.

Now that DSM7 is out of beta and "out in the wild" with a few versions under its belt, is there any news on the update to this script? I've used it with DSM6 and loved it! The script refuses to function on DSM7 and throws up a daily error in my notifications.

Thanks in advance & keep up the great work!

If you're on the fence, I'd say it's safe to upgrade to DSM7 at this stage. I've done it with my 216+II and it's working great. Snappier UI and everything.

**Comment by rhys-saldanha** [comment]
I'm a very new Synology user and as such I've been on DSM7 since day 1 - I don't really have a choice! Hopefully this tool can be updated to work with DSM7.

**Comment by braxtone** [comment]
This looks abandoned per https://github.com/michealespinola/syno.plexupdate/issues/4 so I think you're better off with the fork referenced in there.

**Comment by hobbesjaap** [comment]
This is great, didn't realise there was an updated fork. Trying it out now. Thanks!

**Comment by michealespinola** [comment]
The code has been updated to support DSM

**Comment by braxtone** [comment]
Hooray! Thanks!
