### ISSUE TITLE
Roll back to 3.0.3 for DSM6?

### ISSUE THREAD

**Issue by g6nhu** [michealespinola/syno.plexupdate#24]
I'm running DSM6 on my Synology DS1019+ and the script automatically updated to V4 a couple of nights ago.

I have no desire to update to DSM7, is there any way I can roll this script back to 3.0.2 please?

(/edit - I meant 3.0.2 in the subject, not 3.0.3)

Thanks.

**Comment by michealespinola** [comment]
Absolutely. Just replace the script with the 3.0.2 version and be sure to set '`SelfUpdate=0'` in the config.ini to stop auto-updates of the script. You can download v3.0.2 script raw here:

https://raw.githubusercontent.com/michealespinola/syno.plexupdate/v3.0.2/syno.plexupdate.sh

or zipped:

https://github.com/michealespinola/syno.plexupdate/archive/refs/tags/v3.0.2.zip

Let me know if there is anything else I can do to help you roll back.

**Comment by g6nhu** [comment]
Thanks, that's all rolled back and working.
