### ISSUE TITLE
wget: missing URL

### ISSUE THREAD

**Issue by neogamaes** [michealespinola/syno.plexupdate#34]
Hi,

Thanks for your script. It seems perfect for me. However, I just tried to use the v3.0.2 on my DS218j with DSM6.2.4 but I get the error message when trying to download the new plex package: 

wget: missing URL
Usage: wget [OPTION]... [URL]...

Any idea ?

Thank you,
Regards,

**Comment by michealespinola** [comment]
My guess is that the JSON lookup isn't finding a matching release and that the variable that should have been set with the download URL is null.

Please run the following script and post back the "SYNOLOGY NAS INFO" section:

https://github.com/michealespinola/syno.plexupdate/blob/master/Tools/syno.plexinfo.sh

This should give me what I need to verify against the JSON query to see if there is something missing or mismatched. Be sure to redact anything personally identifiable.

**Comment by michealespinola** [comment]
I should have noted that the "info" script is made for DSM 7, so it will likely throw errors about the Plex parts of the output. That's fine because I only need the top NAS-related info.

**Comment by neogamaes** [comment]
Thank you for your quick answer.

Running syno.plexinfo I get:

SYNO.PLEX INFO SCRIPT for DSM 7

ping: myip.opendns.com: No address associated with hostname
/volume1/Backup/Script/autoplexupdate/syno.plexinfo.sh: line 68:
***@***.***/PlexMediaServer/Plex Transcoder: No such file or
directory
/volume1/Backup/Script/autoplexupdate/syno.plexinfo.sh: line 69:
***@***.***/PlexMediaServer/Plex Transcoder: No such file or
directory
find: `/AppData/Plex Media Server/Codecs': No such file or directory
head: cannot open '/AppData/Plex Media Server/Codecs/.device-id' for
reading: No such file or directory
grep: /AppData/Plex Media Server/Preferences.xml: No such file or directory
grep: /AppData/Plex Media Server/Preferences.xml: No such file or directory
grep: /AppData/Plex Media Server/Preferences.xml: No such file or directory
grep: /AppData/Plex Media Server/Preferences.xml: No such file or directory
SYNOLOGY NAS INFO:
---------------
       Nodename: DiskStation
        DSM ver: 6.2.4-25556 Update 6
          Model: DS218j-j
   Architecture: armv7l (armada38x)
         Kernel: Linux (3.10.105)
  Admin account: Disabled
    Internal IP: 192.168.1.23
    External IP:

TIME ZONE INFO:
---------------
Europe/Amsterdam

PLEX MEDIA SERVER INFO:
---------------
  Friendly Name:
        PMS ver:
     Transcoder:  ()
 Update Channel: Public
      Device-ID:
     Machine-ID:
   Online Token:

PLEX DIRECTORY REFERENCE:
---------------
----------------


I am not sure this is really helpful. For information,  this is the message
I get from syno.plexupdate, maybe more helpful:

Tâche : Plex Auto Update
Heure de début : Wed, 09 Nov 2022 16:39:26 GMT
Heure d’arrêt : Wed, 09 Nov 2022 16:39:33 GMT
État actuel : 1 (Interrompu)
Sortie standard/erreur :

SYNO.PLEX UPDATE SCRIPT v3.0.2

         Script: syno.plexupdate1.sh v3.0.2
     Script Dir: /volume1/Backup/Script/autoplexupdate
    Running Ver: 3.0.2
                 * No new version found.

       Synology: DS218j-j (armv7l), DSM 6.2.4-25556 Update 6
       Plex Dir: /volume1/Plex/Library/Application Support/Plex Media Server
     Plex Token: xxxxxxxxxxx
    Running Ver: 1.29.1.6276
     Online Ver: 1.30.0.6359 (Beta Channel)
       Released: 2022-10-31 23:22:39+01:00 (8+ days old)
                 * Newer version found!

    New Package:
    Package Age: 8+ days old (7+ required for install)

INSTALLING NEW PACKAGE:
----------------------------------------
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

 * Package download failed, skipping install...
----------------------------------------

    Update from: 1.29.1.6276
             to: 1.30.0.6359 succeeded!

NEW FEATURES:
----------------------------------------
* (PlexMatch) Add support for pattern matching (#13899)
* (Scheduled Tasks) Perform periodic metadata refreshes on TV shows too
(#13920)
* (Transcoder) Support zero-copy hardware transcoding on macOS (#13904)
----------------------------------------

FIXED FEATURES:
----------------------------------------
* (Artwork) Restrict client artwork screensaver to items user is allowed to
access (#13916)
* (Music) Some tracks may show lyrics being available when they are not
(#13926)
* (Scanner) Episodes of series with names beginning with a single digit
could be mis-matched (#13921)
----------------------------------------

Thanks for your support

Le mer. 9 nov. 2022 à 16:17, Micheal Espinola ***@***.***> a
écrit :

**Comment by michealespinola** [comment]
JSON query for "`.nas."Synology".releases[]`" for non-DSM 7 shows that there is not an exact match for your "`armv7l`" architecture:

```
{
  "label": "Intel 32-bit (x10 Series, DS415play, and DS214play)",
  "build": "linux-x86",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.30.0.6359-1185e28d9/synology/PlexMediaServer-1.30.0.6359-1185e28d9-x86_DSM6.spk",
  "checksum": "5c5ac7860f40aa985bad1aca2da5ff57083d1cd0"
}
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.30.0.6359-1185e28d9/synology/PlexMediaServer-1.30.0.6359-1185e28d9-x86_64_DSM6.spk",
  "checksum": "405586624b58e6a0d2b9352fe6b98a2d31889313"
}
{
  "label": "ARMv8 (x18 Series)",
  "build": "linux-aarch64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.30.0.6359-1185e28d9/synology/PlexMediaServer-1.30.0.6359-1185e28d9-aarch64_DSM6.spk",
  "checksum": "de934ff9315eb74939504a5748b076a9dbc7fa93"
}
{
  "label": "ARMv7 (x13 Series, x14 Series (excluding DS414j), DS115j, RS815, and DS216se)",
  "build": "linux-armv7hf",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.30.0.6359-1185e28d9/synology/PlexMediaServer-1.30.0.6359-1185e28d9-armv7hf_DSM6.spk",
  "checksum": "72c4a0b8a21d409d3ef1296ff77de42fc3831b1c"
}
{
  "label": "ARMv7 (x15 Series (excluding DS115j and RS815), x16 Series (excluding DS216se), x17 Series, x18 Series, and DS414j)",
  "build": "linux-armv7neon",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.30.0.6359-1185e28d9/synology/PlexMediaServer-1.30.0.6359-1185e28d9-armv7neon_DSM6.spk",
  "checksum": "157fe428265e9149b12177f85f0f31bc8fc67d0a"
}
```

Are either of the bottom "`ARMv7`" listings applicable for your device? If so, I should be able to insert a substitution for your device. I'm guessing its the last entry that applies to the 'x18 Series'?

**Comment by neogamaes** [comment]
Yes you are correct. If I try to download the package manually via Plex it
downloads this
one: PlexMediaServer-1.30.0.6359-1185e28d9-armv7neon_DSM6.spk which is the
last one in your list.

Le mer. 9 nov. 2022 à 17:59, Micheal Espinola ***@***.***> a
écrit :

**Comment by michealespinola** [comment]
Great, thank you for confirming that! Give me a bit and I will write in a shim for your model architecture to use that build

**Comment by neogamaes** [comment]
Great thx. Let me know when available.

Le mer. 9 nov. 2022 à 18:52, Micheal Espinola ***@***.***> a
écrit :

**Comment by michealespinola** [comment]
Please try v3.1.0 for DSM 6:

https://github.com/michealespinola/syno.plexupdate/blob/master/Tools/syno.plexupdate-3.1.0-DSM6.sh

**Comment by neogamaes** [comment]
That works perfectly fine. Thx a lot.

Le mer. 9 nov. 2022 à 22:22, Micheal Espinola ***@***.***> a
écrit :
