### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TrickToo** [michealespinola/syno.plexupdate#37]
I'm getting the following error when I attempt to run the script.

This is from the email report.

**Comment by michealespinola** [comment]
Not enough info. Which DS? Which version of DSM? Which version of the syno.plexupdate script?

**Comment by TrickToo** [comment]
I think it's working now. I clicked goto file on the main page and grabbed the script from there. Then i went back and grabbed the zip file and replaced the script file and got the following response.
Task Scheduler has completed a scheduled task.

Task: Plex Update
Start time: Sun, 11 Dec 2022 09:34:59 GMT
Stop time: Sun, 11 Dec 2022 09:35:02 GMT
Current status: 1 (Interrupted)
Standard output/error:

SYNO.PLEX UPDATE SCRIPT v4.1.0 for DSM 7

* CONFIGURATION FILE (config.ini) IS MISSING, CREATING DEFAULT SETUP...

Script: syno.plexupdate.sh
Script Dir: /volume1/TricksNAS/Scripts
Running Ver: 4.1.0
Online Ver: 4.1.0
Released: 2022-07-18 13:34:39-04:00 (145+ days old)
* No new version found.

Synology: DS1621+ (x86_64), DSM 7.1.1-42962 Update 2
Plex Dir: /volume1/PlexMediaServer/AppData/Plex Media Server
Plex Token: blah blah blah (NEVER POST OR SHARE THIS)
Running Ver: 1.30.0.6486
Online Ver: 1.29.2.6364 (Public Channel)
Released: 2022-11-01 08:14:19-04:00 (40+ days old)
* No new version found.



From TricksNAS

This looks like the correct response.

    On Sunday, December 11, 2022 at 09:31:45 AM EST, Micheal Espinola ***@***.***> wrote:  
 
 


Not enough info. Which DS? Which version of DSM? Which version of the syno.plexupdate script?

**Comment by michealespinola** [comment]
Looks good. If your initial attempt was a copy/paste of the script via a web browser, the formatting of the script may have gotten mangled - especially if between Windows/Linux(Synology).  I was going to recommend redownloading the file, so I'm glad you beat me to it.
