### ISSUE TITLE
root partition does not have enough space

### ISSUE THREAD

**Issue by pankrusheff** [michealespinola/syno.plexupdate#44]
[syno.plexupdate.sh.log](https://github.com/michealespinola/syno.plexupdate/files/12787130/syno.plexupdate.sh.log)
The script says it has successfully bonnovated the version. But in fact an error appeared (you can see it in the logs) ` "code":279, "description": "root partition does not have enough space".`
The script didn't process this error and I don't know what to do with it. Help me please

**Comment by michealespinola** [comment]
This isn't a fault from the script. This is a system warning that the root partition is low on free space. Something, at some point, improperly saved data to your root partition and is/has caused it to fill. Your root partition (`/root`) should not contain anything not system-related. 

Via an SSH terminal, log in to your Synology with an account that has admin privileges and manually see what is in the /root directory hierarchy. Typically, there will only be a few hidden text files that begin with '`.`'.  Files beginning with '`.`' are ignored by default with normal use of `ls`. To see them with `ls` you need to use the `--all` option.

As an example, here is what my `/root` looks like on all of my Synology NAS's:

```
# dir /root
total 20
drwx------  2 root root 4096 Sep 25 23:33  .
drwxr-xr-x 26 root root 4096 Sep 28 21:12  ..
-rw-r--r--  1 root root    0 Apr 19 09:02 'FOR SYSTEM USE ONLY. DO NOT UPLOAD FILES HERE.'
-rw-r--r--  1 root root 1313 Apr 19 09:02  .profile
-rw-r--r--  1 root root 2043 Apr 19 09:02  .profile.size_check
-rw-r--r--  1 root root  282 Oct  2 18:06  .wget-hsts
```

or...

```
# ls --all /root
 .   'FOR SYSTEM USE ONLY. DO NOT UPLOAD FILES HERE.'   .profile.size_check
 ..   .profile      
```

**Comment by pankrusheff** [comment]
Thank you. I assumed there was something wrong with the system :) Any ideas how to fix it? I'm not too advanced to do it alone. But the script didn't update the version, so it didn't fulfill its task, so it would be correct to write about the error in the log and not to say that the PLEX version is updated. What do you think?

**Comment by pankrusheff** [comment]
Figured it out. Thank you very much for the script. For the quick response too. Good luck to you. Thanks for sharing. Closing the ticket

**Comment by michealespinola** [comment]
Glad to hear you worked your way through it. As you experienced, when it happens, software installs can/will fail. It's happened to me a couple of times in the past as well. It's annoying that you can't easily resolve this kind of issue through the DSM.
