### ISSUE TITLE
Update fails on PLEX restart / DS218+ / DSM7 / script 4.4.0

### ISSUE THREAD

**Issue by bedouin345** [michealespinola/syno.plexupdate#45]
I face an issue with the script: 
it discovers the right version of PLEX, waits 7 days then installs it... and nothing, It seems to stop after 15mn time-out. 
The package is unavailable and has only greyed out options. The PLEX process is considered "dead".
I cannot even Kill processes and have to manually restart the NAS.

I faced the issues for last 2 updates and would appreciate help. 

The log does not help me much, copy below :  
 

```
SYNO.PLEX UPDATE SCRIPT v4.4.0 for DSM 7

         Script: syno.plexupdate.sh
     Script Dir: /volume1/docker/syno.plexupdate
    Running Ver: 4.4.0
     Online Ver: 4.4.0
       Released: 2023-05-01 16:17:15+03:00 (410+ days old)
                 * No new version found.

       Synology: DS218+ (x86_64), DSM 7.2-64570 Update 1
       Plex Dir: /volume1/PlexMediaServer/AppData/Plex Media Server
    Running Ver: 1.40.2.8395
     Online Ver: 1.40.3.8555 (Public Channel)
       Released: 2024-06-07 10:46:47+03:00 (7+ days old)
                 * Newer version found!

    New Package: PlexMediaServer-1.40.3.8555-fef15d30c-x86_64_DSM7.spk
    Package Age: 7+ days old (7+ required for install)

INSTALLING NEW PACKAGE:
----------------------------------------
Downloading PlexMediaServer package:

Stopping PlexMediaServer service:
{"action":"stop","beta":false,"error":{"code":0},"finished":true,"language":"enu","last_stage":"stopped","package":"PlexMediaServer","pid":4140,"scripts":[{"code":0,"message":"","type":"stop"}],"stage":"stopped","status":"stop","status_code":324,"status_description":"translate from systemd status","success":true,"username":"","version":"1.40.2.8395-7000"}

Installing PlexMediaServer update:
{"error":{"code":0},"results":[{"action":"upgrade","beta":false,"betaIncoming":false,"error":{"code":0},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"postupgrade","package":"PlexMediaServer","packageName":"Plex Media Server","pid":4765,"scripts":[{"code":0,"message":"","type":"preupgrade"},{"code":0,"message":"","type":"preuninst"},{"code":0,"message":"","type":"postuninst"},{"code":0,"message":"","type":"preinst"},{"code":0,"message":"Installation Successful!
"type":"postinst"},{"code":0,"message":"","type":"postupgrade"}],"spk":"/volume1/docker/syno.plexupdate/Archive/Packages/PlexMediaServer-1.40.3.8555-fef15d30c-x86_64_DSM7.spk","stage":"installed_and_stopped","status":"stop","status_code":273,"status_description":"translate from systemd status","success":true,"username":"","version":"1.40.2.8395-7000"}],"success":true}

Starting PlexMediaServer service:
{"action":"prepare","error":{"action":"start","code":318,"description":"Failed to finish unit execution due to timeout"},"last_stage":"prepare_start","stage":"start","success":false}
----------------------------------------

    Update from: 1.40.2.8395
             to: 1.40.3.8555 succeeded!

NEW FEATURES:
----------------------------------------
* (Auto Update) 32 bit installations of Plex Media Server running on 64 bit windows will be upgraded to 64 bit installations via auto update. (PM-1102)
* (Web) Updated to 4.129.1
----------------------------------------

FIXED FEATURES:
----------------------------------------
* (Analysis) Analysis of items would be performed for chapter thumbs even if chapter thumb generation was disabled (PM-1212)
* (Analysis) Slow DB queries caused analysis to be slow to start (PM-1211)
* (GPU) Server would crash on startup if a user was running windows with Nvidia drivers installed but no Nvidia GPU. (PR-14862)
* (History) Grandparent title and guid could get reversed
* (MediaAnalysis) Part created_at and updated_at were row created/update times instead of file (PM-1534)
* (Smart Collections) DB Optimize would make smart collections uneditable (PM-900)
* (Transcode) Tone mapping would fail for some devices on linux Kernel 5.17 or newer. (PR-1412)
----------------------------------------
```

**Comment by michealespinola** [comment]
Thank you for posting your log data. Your script dir lists as '/volume1/docker/syno.plexupdate'. Are you running this script in a docker container? What is the status of the of the PMS app after a reboot? Is it still dead or greyed-out?

**Comment by bedouin345** [comment]
Hey, thank you for the quick answer.
And no, PLEX is running as a native app on my NAS. I have stored all my scripts and config files in a /docker folder for ease of use & Access.

Once the app update fails, I am unable to do anything, and even the DSM reboot just hangs. I can see the DSM reboot does stop a lot of processes but it seems to get stuck by PMS.
The only solution then is a hard reboot from the power switch ! 
Once restarted, I faced 2 situations : 
- last month, PMS was totally greyed out and status was "repairing" - a neverending state. I eventually had to unsintall and reinstall from scratch PMS
- last week, PMS started ok with the new version
 
I went through the debug log without any hint as well. Really clueless on that situation

**Comment by michealespinola** [comment]
You and I are both running the same installed package ('PlexMediaServer-1.40.3.8555-fef15d30c-x86_64_DSM7.spk'), on the Apollolake x86_64 architecture. I'm running PMS on a DS1019+, so my unit is a slightly more robust model, but its the same architecture.

To confirm what you said: A manual uninstall/reinstall worked fine in the past after experiencing this issue, but it fails to start the process via the script? Was this a manually selected download from the Plex website, after which you manually installed it via the DSM web interface? Comparing your log to mine; our installation log portion are identical except for the PIDs. The service stop/start functionality is very straightforward and uses built-in Synology utilities. 

Your script directory should contain the automatically generated file 'syno.plexupdate.sh.debug'. This is a raw log of everything that the script processed, and may contain/expose an unseen error or issue. If you would, please email this to me as an attachment to michealespinola[@]gmail.com. Based on your terminal output log, the file should be located here on your system:

    /volume1/docker/syno.plexupdate/syno.plexupdate.sh.debug

* **Important Note:** Your private Plex Token will be exposed in this log. Please feel free to scrub this information from the log file before sending it. You can perform a search for "`Token=`" to find all instances of it. There are typically (3) instances of a token in the debug file. If you don't wish to share this log for privacy reasons (the raw log will also contain other system identifiers that you are also welcome to scrub if you wish), we can continue with additional questions and other troubleshooting methods, for which I will continue below to save time:

The obvious outlier that I can ascertain between the two of us is the version of DSM7 you are on. You are on '7.2-64570 Update 1', while I am on '7.2.1-69057 Update 5'.  If you are confident/able, it would be great if you could try to install the package that the script downloaded via the ssh/bash terminal. If everything I read in your log was correct, the command would be this on your system:

    /usr/syno/bin/synopkg install '/volume1/docker/syno.plexupdate/Archive/Packages/PlexMediaServer-1.40.3.8555-fef15d30c-x86_64_DSM7.spk'

You can choose to first issue a package stop as the script does, but it's really not necessary on DSM7. I left the manual stop in the script for those trying to make the script work in other environments.

If you don't feel comfortable doing this, I have some recommendations, but no straightforward solutions:

1. *Update to the latest version of DSM*. I wouldn't normally recommend this as a solution to a  script problem, but I think that the problem you are experiencing might be systemic, as its a failure of a basic built-in tool's functionality.
2. *Contact Synology*. I absolutely hate advising this, but there is a significant lack of public knowledge regarding their internal error codes. I have be searching through everything that I can, but I can't find anything regarding any system or package start error code "318". This also doesn't seem to coincide with any standard *nix system error code.
3. *Contact Plex*. There is a possibility that there is a compatibility issue with your specific model of NAS. There might be a system resources issue.

Don't take the last two recommendations as a dismissal. I'm ready to help walk-through you through additional attempts at troubleshooting if you are up to it.

**Comment by michealespinola** [comment]
I've reviewed your debug log and did not find anything anomalous. It's downloading the correct package via the Plex API and website, and performing all of the steps and checks properly. The failure, as far as I can tell, is unique to your environment; in that after a successful installation, there is a package start failure with error code "318". 

The API error code list that I have for Synology skips right over the 200 and 300 number range, and I cannot find any references from any other resources that I am aware of.

At this point I still recommend getting updated to the latest version of DSM7. I don't see anything specific in the [DSM7 update release notes](https://www.synology.com/en-us/releaseNote/DSM) addressing an issue like this, but this could be an edge case specific to Plex.

How much RAM does your DS218+ have?

**Comment by bedouin345** [comment]
Thank you
I updated the DSM and will see what happens at next Plex update

Thanks for the tip on error 318, I also did a search without any luck. Do
you think this qualifies for a support ticket with Synology ?.

**Comment by michealespinola** [comment]
I would. I would try to be proactive about it in case it happens again. Any information that Synology or even Plex support could provide might prove to be beneficial. Plex might even be particularly interested in knowing this data because it may affect how the are developing the app and which platforms are viable platforms. If it turns out to be a system resource issue, it's possible that Plex has bloated the app or has introduced some sort of bug that is preventing it from starting. But because we cant understand Synology's error code, we can't be certain.

If I were you, I would open up issues with them both. The update script is really quite basic in what it does, especially in terms of the stop/install/start aspect. The only thing that I would say is slick/trick about what the script does is in terms of using the website APIs to find and update with the correct version based on what is automatically self-determined from the NAS.

I don't mean to seem like I am brushing off the problem on to others, but I can't do this part for you, because I don't have your hardware and can't recreate the issue. I wouldn't be able to interact with Synology or Plex support in a meaningful way. They need to communicate with whomever can recreate the problem (if willing), or at least can provide them with additional specific information directly.

I am going to close this issue for now. If you learn anything from Synology or Plex, and/or this problem happens again, feel free to re-open it and we'll see what can be done at that time.

**Comment by bedouin345** [comment]
Thank you again.
I know you are not brushing off the issue, don't worry.

I noticed there is a new update coming and will see in a couple days if
this is working now that I upgraded the DSM version.
 Will keep you informed.

**Comment by michealespinola** [comment]
Please do, and best of luck!

**Comment by bedouin345** [comment]
It worked. Thank you
