### ISSUE TITLE
New version not detected correctly

### ISSUE THREAD

**Issue by p4xel** [michealespinola/syno.plexupdate#46]
It appears there was a change in 5.json label names.
`jq -r '.nas.synology.version'` returns Null

After changing version changing part to following it works well
```
  NewVersion=$(echo "$DistroJson" | jq -r '.nas."Synology (DSM 7)".version')
  NewVersion=$(echo "$NewVersion" | grep -oP '^.+?(?=\-)')
  NewVerDate=$(echo "$DistroJson" | jq -r '.nas."Synology (DSM 7)".release_date')
  NewVerAddd=$(echo "$DistroJson" | jq -r '.nas."Synology (DSM 7)".items_added')
  NewVerFixd=$(echo "$DistroJson" | jq -r '.nas."Synology (DSM 7)".items_fixed')
```

**Comment by michealespinola** [comment]
Hi, thanks for submitting a bug report! I can confirm the issue as well as your proposed fix for it.  Thank you! I will work on submitting a fixed release shortly.

**Comment by michealespinola** [comment]
Version 4.5.0 has been released
