### ISSUE TITLE
Consider contributing to this existing project

### ISSUE THREAD

**Issue by cowboy** [michealespinola/syno.plexupdate#5]
FWIW, I wrote this a while back, and it's been working well. If you have any interests in consolidating our work, LMK!

https://github.com/cowboy/synology-update-plex

**Comment by michealespinola** [comment]
The same goes both ways if you think there is something that could be enhanced or made more effective here. I'm in a bit of a holding pattern while DSM7 is in beta. Scripts like these might even not be necessary in the near future.

**Comment by cowboy** [comment]
Sure, I'll take a look and see if there's anything I can contribute!
