### ISSUE TITLE
"Online Ver" in 4.6.9 is Nonexistent

### ISSUE THREAD

**Issue by bauzer714** [michealespinola/syno.plexupdate#52]
From 4.6.8 to 4.6.9 the version the "Online version" has been added which per the git log is intended to show when it's a "null query".  If the below screenshots between versions matches the expectations; it's confusing as it "exited 1" and sent me a notification. 

![image](https://github.com/user-attachments/assets/1085f0b3-6958-4f7c-985d-291c64e4733b)

**Comment by michealespinola** [comment]
This is technically an error condition because Plex doesn't have a public version for 7.2.2 available through their API. There is however a beta version available through their API for 7.2.2. I absolutely appreciate the confusion, but I'm not sure there is a better alternative for this circumstance. It's unique and shouldn't be happening. Presumably, it wont be happening for long.

I'm open to suggestions. I receive the same log status email every morning.

**Comment by bauzer714** [comment]
Ah - well that makes sense. I don't typically apply beta's so I forgot that I had done that.

Seems like this is an edge case scenario that coding around is something that would add cruft and the solution may not be robust enough to work for the future anyway.  

Good to close by me, unless you want to leave it open.

**Comment by michealespinola** [comment]
I've considered trying to do something as a one-off in this situation, but I don't think that its worth the risk of potentially introducing issues in the code or doing anything that avoids or circumvents the knowledge of the users of the script.  [Plex has (3) stand-alone pseudo-public version installers for an update compatible with 7.2,2](https://github.com/michealespinola/syno.plexupdate/issues/50#issuecomment-2326998799), (as referenced in that linked comment), and I really though that by now they would have been added into the API. 

Perhaps I should create a wiki article regarding a "Nonexistent" online version, and have the logged output of the script refer to it if/when it presents itself, so at least there is an immediate information trail to follow.

But of course, I see things from my own perspective, so if you have anything to add to this or any ideas for what you consider would be a helpful approach; I'm happy to entertain them.

**Comment by michealespinola** [comment]
**PLEASE NOTE:** DSM 7.2.2-72803 has been recalled. It has been replaced with DSM 7.2.2-72806. It is available through the Operating System direct download link, and not through the typical DSM version > DSM version update path.

**Comment by bauzer714** [comment]
> **PLEASE NOTE:** DSM 7.2.2-72803 has been recalled. It has been replaced with DSM 7.2.2-72806. It is available through the Operating System direct download link, and not through the typical DSM version > DSM version update path.

Thanks for sharing. Applied the update.

> ** Perhaps I should create a wiki article regarding a "Nonexistent" online version, and have the logged output of the script refer to it if/when it presents itself, so at least there is an immediate information trail to follow.

It depends how many reasons are likely.  The fewer, the more likely I'd advocate for just putting it in script. 

> ** Nonexistant (e.g. No <Channel> version available for your OS version, <reason 2>)

**Comment by michealespinola** [comment]
I appreciate the feedback.
